destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/core-paas-pdf"
port: 4010
product: core-paas
print_title: Jekyll theme for documentation — core-paas product
print_subtitle: version 6.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: core-paas_sidebar
